### ISSUE TITLE
issues about service config

### ISSUE THREAD

**Issue by caitong93** [caicloud/charts#2]
some issues:
1) should support multi-port
2) allow random node port

below is a example format

``` yaml
name: string
// True to create NodePort service
nodePort: bool
portMapping:
  - port: int
    targetPort: int
    protocol: string
    # range [30000,32767], 0 to use random port
    nodePort: int

```

@kdada PTAL
